import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import { cn } from "./lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "",
          "font-sans flex flex-col w-full max-w-screen-2xl mx-auto"
        )}
      >
        <Header />
        <main className="grow bg-sky-400">{children}</main>
      </body>
    </html>
  );
}
